// icons.h
// Important note
// ==============
// This file is automatically generated by the script create_svgs_header.py.
// Edits will be overwritten on the next run.

#ifndef SVGS_H
#define SVGS_H

#include <wx/wxprec.h>

#ifndef WX_PRECOMP
#include <wx/wx.h>
#endif


static const wxString SVG_PAUSE = 
    R"svg(
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   width="64"
   height="64"
   viewBox="0 0 16.933333 16.933333"
   version="1.1"
   id="svg1"
   inkscape:version="1.4.2 (ebf0e94, 2025-05-08)"
   sodipodi:docname="pause.svg"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <sodipodi:namedview
     id="namedview1"
     pagecolor="#ffffff"
     bordercolor="#000000"
     borderopacity="0.25"
     inkscape:showpageshadow="2"
     inkscape:pageopacity="0.0"
     inkscape:pagecheckerboard="0"
     inkscape:deskcolor="#d1d1d1"
     inkscape:document-units="mm"
     inkscape:zoom="8.718206"
     inkscape:cx="23.169904"
     inkscape:cy="38.59739"
     inkscape:window-width="1920"
     inkscape:window-height="1131"
     inkscape:window-x="0"
     inkscape:window-y="0"
     inkscape:window-maximized="1"
     inkscape:current-layer="layer1" />
  <defs
     id="defs1" />
  <g
     inkscape:label="Layer 1"
     inkscape:groupmode="layer"
     id="layer1">
    <rect
       style="fill:#ffdbbe;fill-opacity:1;stroke:none;stroke-width:0.965452;stroke-dasharray:none;stroke-opacity:1"
       id="rect4"
       width="12.805574"
       height="12.789179"
       x="2.0638795"
       y="2.0720773" />
    <rect
       style="fill:#000000;fill-opacity:1;stroke:none;stroke-width:0.57554;stroke-dasharray:none;stroke-opacity:1"
       id="rect5"
       width="4.550818"
       height="12.789179"
       x="2.0638795"
       y="2.0720773" />
    <rect
       style="fill:#000000;fill-opacity:1;stroke:none;stroke-width:0.57554;stroke-dasharray:none;stroke-opacity:1"
       id="rect6"
       width="4.550818"
       height="12.789179"
       x="10.318636"
       y="2.0720773" />
  </g>
</svg>

)svg";
static const wxString SVG_EDIT = 
    R"svg(
<?xml version="1.0" encoding="utf-8"?>

<!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->
<svg width="800px" height="800px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<g id="style=fill">
<g id="edit">
<path id="Subtract" fill-rule="evenodd" clip-rule="evenodd" d="M18.9405 3.12087L21.0618 5.24219C22.2334 6.41376 22.2334 8.31326 21.0618 9.48483L19.2586 11.288L12.8947 4.92403L14.6978 3.12087C15.8694 1.94929 17.7689 1.94929 18.9405 3.12087ZM11.834 5.98469L3.70656 14.1121C3.22329 14.5954 2.91952 15.2292 2.84552 15.9086L2.45151 19.5264C2.31313 20.7969 3.38571 21.8695 4.65629 21.7311L8.27401 21.3371C8.95345 21.2631 9.58725 20.9594 10.0705 20.4761L18.1979 12.3486L11.834 5.98469Z" fill="#000000"/>
</g>
</g>
</svg>
)svg";
static const wxString SVG_HAMMER = 
    R"svg(
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   width="64"
   height="64"
   viewBox="0 0 16.933333 16.933333"
   version="1.1"
   id="svg1"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <defs
     id="defs1" />
  <g
     id="layer1">
    <path
       id="hammer"
       d="m 16.231317,12.620691 c -0.494256,0.512757 -1.744824,1.806189 -2.775536,2.846003 L 9.1422808,10.856387 11.724921,8.2737405 Z M 8.2161291,9.9305581 10.798768,7.3479112 c 0,0 -1.3116189,-1.0008382 -1.1908182,-1.6259621 C 9.7287583,5.0968278 10.001536,4.2128901 11.901258,3.4286502 13.800649,2.644733 15.572742,2.5739371 15.572742,2.5739371 l 0.06365,-0.8563362 c 0,0 -4.365777,-0.6595401 -6.6720698,0.1597758 -2.3062907,0.8193146 -4.9149126,3.9036788 -4.9149126,3.9036788 0,0 0.4549601,1.4915183 -0.3244078,2.2712154 C 2.9453068,8.8319682 1.8973737,7.9330925 1.8973737,7.9330925 L 0.70201681,9.4509165 3.7185118,12.467088 5.2334157,11.269125 c 0,0 -0.7170216,-1.07391 -0.00842,-1.7168877 1.5246477,-1.38371 2.9911704,0.3783196 2.9911704,0.3783196 z"
       style="clip-rule:evenodd;fill-rule:evenodd;stroke-width:0.324738;stroke-linejoin:round;stroke-miterlimit:2" />
  </g>
</svg>

)svg";
static const wxString SVG_START = 
    R"svg(
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   width="64"
   height="64"
   viewBox="0 0 16.933333 16.933333"
   version="1.1"
   id="svg1"
   inkscape:version="1.4.2 (ebf0e94, 2025-05-08)"
   sodipodi:docname="start.svg"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <sodipodi:namedview
     id="namedview1"
     pagecolor="#ffffff"
     bordercolor="#000000"
     borderopacity="0.25"
     inkscape:showpageshadow="2"
     inkscape:pageopacity="0.0"
     inkscape:pagecheckerboard="0"
     inkscape:deskcolor="#d1d1d1"
     inkscape:document-units="mm"
     inkscape:zoom="8.718206"
     inkscape:cx="23.169904"
     inkscape:cy="38.59739"
     inkscape:window-width="1920"
     inkscape:window-height="1131"
     inkscape:window-x="0"
     inkscape:window-y="0"
     inkscape:window-maximized="1"
     inkscape:current-layer="layer1" />
  <defs
     id="defs1" />
  <g
     inkscape:label="Layer 1"
     inkscape:groupmode="layer"
     id="layer1">
    <g
       id="g4"
       transform="matrix(1.4598645,0,0,1.2512135,-5.5235816,-2.496553)">
      <path
         style="fill:#000000;fill-opacity:1;stroke:none;stroke-width:0.117646;stroke-opacity:0"
         d="M 5.3327411,3.7642281 V 8.7621434 H 13.833761 Z"
         id="path1" />
      <path
         style="fill:#000000;fill-opacity:1;stroke:none;stroke-width:0.117729;stroke-opacity:0"
         d="M 5.3266284,13.759911 V 8.7621434 h 8.5132456 z"
         id="path4" />
    </g>
  </g>
</svg>

)svg";
static const wxString SVG_STOP = 
    R"svg(
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   width="64"
   height="64"
   viewBox="0 0 16.933333 16.933333"
   version="1.1"
   id="svg1"
   inkscape:version="1.4.2 (ebf0e94, 2025-05-08)"
   sodipodi:docname="stop.svg"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <sodipodi:namedview
     id="namedview1"
     pagecolor="#ffffff"
     bordercolor="#000000"
     borderopacity="0.25"
     inkscape:showpageshadow="2"
     inkscape:pageopacity="0.0"
     inkscape:pagecheckerboard="0"
     inkscape:deskcolor="#d1d1d1"
     inkscape:document-units="mm"
     inkscape:zoom="8.718206"
     inkscape:cx="23.169904"
     inkscape:cy="38.59739"
     inkscape:window-width="1920"
     inkscape:window-height="1131"
     inkscape:window-x="0"
     inkscape:window-y="0"
     inkscape:window-maximized="1"
     inkscape:current-layer="layer1" />
  <defs
     id="defs1" />
  <g
     inkscape:label="Layer 1"
     inkscape:groupmode="layer"
     id="layer1">
    <rect
       style="fill:#000000;fill-opacity:1;stroke:none;stroke-width:0.965452;stroke-dasharray:none;stroke-opacity:1"
       id="rect4"
       width="12.805574"
       height="12.789179"
       x="2.0638795"
       y="2.0720773" />
  </g>
</svg>

)svg";

#endif  // SVGS_H